name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-index:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Install requirements
      run: ./req.sh
    - name: Re-build index page
      run: ./nav.sh
    - name: (debugging)
      if: failure()
      run: |
        more tmp/* | cat
        cat index.md
    - name: Commit changes to PR
      if: success()
      run: |
        git config user.name 'Jethro Lee'
        git config user.email 'dlemfh96@gmail.com'
        git commit -am "Automated build"
        git push
